name: Deploy to server
# not work yet 
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 192.168.0.107 >> ~/.ssh/known_hosts

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Copy project to server
        run: |
          rsync -avz --exclude=node_modules . littlepoet@192.168.0.107:/home/littlepoet/deploy

      - name: Deploy over SSH
        run: |
          ssh littlepoet@192.168.0.107 << 'EOF'
            cd /home/littlepoet/deploy
            docker-compose down
            docker-compose up -d --build
          EOF
