name: API Integration Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    environment: intershipBackend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb

        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb
      NODE_ENV: test
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: apply schema to DB
        run:   npx prisma generate && npx prisma db push

      - name: Seed test data
        run: npm run seed

      - name: Run integration tests
        run: npm test
